### ISSUE TITLE
W ftop param value (10) out of bound (len:0). Selecting all the values from input.

### ISSUE THREAD

**Issue by Nicolas-Fernandez** [ramay/metakraken#1]
Dear Ramay,

I'm a user of Kraken2, Bracken, R heatmap, and last not least, snakemake.
Just discover your pipeline and install it to test it on my data :)
Real pleasure to use your pipeline, rules, config.yaml, and env gestion are very familiar with my practice :)

All look to work great (nice work!) exception last rule, heatmap.

```
W ftop param value (10) out of bound (len:0). Selecting all the values from input.
Traceback (most recent call last):
  File "/data3/projects/GorillaSIVmeta/metakraken/.snakemake/conda/b1853a73/bin/hclust2.py", line 781, in <module>
    dm = DataMatrix( args.inp, args )
  File "/data3/projects/GorillaSIVmeta/metakraken/.snakemake/conda/b1853a73/bin/hclust2.py", line 171, in __init__
    select( self.args.fperc, self.args.ftop )
  File "/data3/projects/GorillaSIVmeta/metakraken/.snakemake/conda/b1853a73/bin/hclust2.py", line 162, in select
    m = sorted(self.table['perc'])[0]
IndexError: list index out of range
```

I check my files:
- merged_metakraken_abundance_table.txt (look ok), but not use
- merged_metakraken_abundance_species.txt (look like just have my sample name on this file ?).

I just replace on your script read_table by read_csv (same error after / before).

I try different value of "topN" in the config.yaml file.
Test also with different params for Bracken threshold.

Looking rule for this file "species.txt", find rule merge_mpa outputed this file.

Could you help me please ?

Best regards,
Nicolas

**Comment by Nicolas-Fernandez** [comment]
Pass this issue changing in config.yaml file Bracken level from "F" to "S".
But i'm interested by Family :/
